### PR TITLE
Feature/percentage mode

### PR DESCRIPTION
**Pull request by athkalia**
Added percentage mode functionality, and updated the sample project with a mini-example

[Review on Reviewable](https://reviewable.io/reviews/jorgecastilloprz/androidfillableloaders/5)

### CODE REVIEW

**Comment by athkalia** [comment]
Hey, I am not quite familiar with Github, or gradle or travis :D So give me a shout on anything that needs updating. 

Cheers

**Comment by athkalia** [comment]
Travis failed, but this is cause it's trying to compile the sample project against the old version of the library (1.02) that doesn't have the percentage. 

How do we handle this ?

**Comment by JorgeCastilloPrz** [comment]
Just change the gradle dependency of the sample project to compile project(:library)
(remove compile 'com.github.jorgecastilloprz:fillableloaders:1.02@aar' so it does not try to get the dependency from maven central)

**Comment by athkalia** [comment]
Shall I change the version under this commit as well ? from 1.02 to 1.03 ?

**Comment by JorgeCastilloPrz** [comment]
Yes, change it to 1.03, please.

**Comment by JorgeCastilloPrz** [comment]
Hi. Can you update your branch and pull the new develop changes? I have merged a master commit which had not been merged time ago. Then i will review and test your code.

Thanks in advance!

**Comment by athkalia** [comment]
I think that they are already included, this branch is already up-to-date with develop and master

**Comment by DVassilev** [comment]
@JorgeCastilloPrz Could you please accept this and push the new version to maven?

**Comment by JorgeCastilloPrz** [comment]
If you want this PR to be merged, i would need:
- A new sample page with the new percentage feature added by XML custom attribute.
- A real sample of a loading which a percentage being changed along the way of a "mock" download. 
- Cleaning the code for the `setPercentage()` method, as it is pretty dirty.

**Comment by athkalia** [comment]
Hey, thanks for your quick review. I'll try to get this done during the coming weekend.

**Comment by JorgeCastilloPrz** [comment]
Hello. Did you work on the last changes we talked about?. Thanks in advance.

**Comment by athkalia** [comment]
hey, sorry for the delay but unfortunately it's gonna get delayed more. I am about to undergo surgery so I doubt this is gonna get looked at for at least a few weeks.

Cheers

**Comment by Letme** [comment]
This seems like it is not moving.  Can we move this a bit just to get it merged in?

**Comment by athkalia** [comment]
Hey, I made a pull request a long time ago but unfortunately I don't have any time to spend on this. Please feel free to continue the pull request.

**Comment by Letme** [comment]
I have sent PR to athkalia and I hope he can merge it in so this PR gets updated with all requested features except making setPercentage pretty (which I have no idea how).

**Comment by athkalia** [comment]
Thanks mate, I'll have a look during the weekend.

**Comment by Letme** [comment]
I would prefer it sooner, since Jorge will also have to take a look at it.

**Comment by athkalia** [comment]
Can you have a look at the checkstyle issues please?

**Comment by Letme** [comment]
@athkalia care to add spaces in FillableLoaderPage.java between the brackets on lines 133 and 135 as that is why CI is failing?

**Comment by athkalia** [comment]
It's passing locally for me, same for you @Letme I take it ?

**Comment by Letme** [comment]
Yeah it is passing locally, I checked also the library:lint (which is failing on Travis) and it is executed and passes (finds just 3 errors instead of 4). None of the Lint warnings are produced by changes in this patch (at least on my local build).
@JorgeCastilloPrz can you advise what you want us to do?

**Comment by Letme** [comment]
I do not have any ideas what might be wrong. Can someone help please?

**Comment by Letme** [comment]
One of the differences I spotted is build number of Java (95 on my computer and 76 on Travis). @athkalia  can you check yours?
```
$ javac -J-Xmx32m -version
javac 1.7.0_95
$ java -Xmx32m -version
java version "1.7.0_95"
```
I could not find any reference on Travis how to fix this.

**Comment by JorgeCastilloPrz** [comment]
Thanks for fixing CI :). I will retake this PR this weekend and work on it to get merged. New version will be deployed to maven central pretty soon!.

Thanks for your work guys :+1:

**Comment by Letme** [comment]
I hope you do not have to do too much. Still I have set-up the Coverity for my fork of the project and it found 2 defects which I will probably get fixed in near future. I would suggest you set up Coverity as that is much stronger static analysis tool than lint and for opensource it is free (github enables usage as service).

**Comment by JorgeCastilloPrz** [comment]
Please, if you could, it would be nice if you can fix those issues before I
review all the changes and merge your code this weekend.

Thanks in advance!

**Comment by Letme** [comment]
I would rather put that on separate PR as this defects are not in scope of
this patch.

**Comment by JorgeCastilloPrz** [comment]
Reviewed 2 of 6 files at r2, 1 of 1 files at r4, 11 of 12 files at r5, 1 of 1 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jorgecastilloprz/androidfillableloaders/5)*

**Pull request merged**
